/**
 * Generated by                   : ct-tfsbuild@SIEGCE8V2006
 * Branch                         : STC Main (18.06)
 * Date                           : 20180426105647
 * Version MySys                  : v18.06
 * Version Socle Technique Client : 2018A
 * TFS hyperlink                  : http://tfs2013qpa.sigcesie.caisse-epargne.fr:8080/tfs/ITCEDefault/MyWay.SocleTechnique/_versionControl/changeset/447789
 * Build droplocation             : \\Vfqitcappc100\tfs_qpa_build\myway\SocleTechnique\STC Main (18.06)\STC Main (18.06)_20180426.1
 */


declare module MyWay.Services {
}
