export const LISTENER_PM_BLOC_INDICATEURS = 'SYNTH_PM_INDIC_LISN';
export const LISTENER_PM_BLOC_ALERTES = 'SYNTH_PM_ALRT_LISN';
export const LISTENER_PM_BLOC_ALERTES_BANDEAU = 'BAND_ALRT_LISN';

export const LISTENER_EI_BLOC_INDICATEURS = 'SYNTH_EI_INDIC_LISN';
export const LISTENER_EI_BLOC_ALERTES_BANDEAU = 'BAND_ALRT_LISN';
export const LISTENER_EI_BLOC_ALERTES = 'SYNTH_EI_ALRT_LISN';

export const NOTIFIER_ALERTE = 'SYNTH_ALRT_NOTF';
