export const LISTENER_PM_BLOC_OPPORTUNITE = 'SYNTH_PM_OPPORTUNITES_LISN';
export const LISTENER_PM_BLOC_OPPORTUNITE_BANDEAU = 'BAND_OPPORTUNITES_LISN';
export const LISTENER_EI_BLOC_OPPORTUNITE = 'SYNTH_EI_OPPORTUNITES_LISN';
export const LISTENER_EI_BLOC_OPPORTUNITE_BANDEAU = 'BAND_OPPORTUNITES_LISN';
