/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Marque de véhicule
 */
export interface BrandsItem {
  /**
   * Marque de véhicule (exemple: Audi, Peugeot, Renault ...)
   */
  brand?: string;
}
