/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateAutoLease} from './initiateAutoLease';

/**
 * Api response for createExpertInquiriesInitiateAutoLeaseV1
 */
export interface CreateExpertInquiriesInitiateAutoLeaseV1Response {
  initiateAutoLease: InitiateAutoLease;
}
