/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateOrganizationManagementService} from './initiateOrganizationManagementService';

/**
 * Api response for createExpertInquiriesInitiateOrganizationManagementServiceV1
 */
export interface CreateExpertInquiriesInitiateOrganizationManagementServiceV1Response {
  initiateOrganizationManagementService?: InitiateOrganizationManagementService;
}
