/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateEcommerce} from './initiateEcommerce';

/**
 * Api response for createExpertInquiriesInitiateEcommerceV1
 */
export interface CreateExpertInquiriesInitiateEcommerceV1Response {
  initiateEcommerce?: InitiateEcommerce;
}
