/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ExpertInquiryIdentityAcceptanceDevice} from './expertInquiryIdentityAcceptanceDevice';
import {ExpertInquiryIdentityAutoLease} from './expertInquiryIdentityAutoLease';
import {ExpertInquiryIdentityBillingService} from './expertInquiryIdentityBillingService';
import {ExpertInquiryIdentityCharacteristics} from './expertInquiryIdentityCharacteristics';
import {ExpertInquiryIdentityConsumerLoan} from './expertInquiryIdentityConsumerLoan';
import {ExpertInquiryIdentityEcommerce} from './expertInquiryIdentityEcommerce';
import {ExpertInquiryIdentityFactoring} from './expertInquiryIdentityFactoring';
import {ExpertInquiryIdentityInsuranceProduct} from './expertInquiryIdentityInsuranceProduct';
import {ExpertInquiryIdentityInternationalImplementation} from './expertInquiryIdentityInternationalImplementation';
import {ExpertInquiryIdentityLoyaltyService} from './expertInquiryIdentityLoyaltyService';
import {ExpertInquiryIdentityOrganizationManagementService} from './expertInquiryIdentityOrganizationManagementService';
import {ExpertInquiryIdentityRetirementProduct} from './expertInquiryIdentityRetirementProduct';
import {ExpertInquiryIdentityServiceVoucher} from './expertInquiryIdentityServiceVoucher';

/**
 *
 */
export interface ExpertInquiryIdentity {
  characteristics?: ExpertInquiryIdentityCharacteristics;
  autoLease?: ExpertInquiryIdentityAutoLease;
  serviceVoucher?: ExpertInquiryIdentityServiceVoucher;
  organizationManagementService?: ExpertInquiryIdentityOrganizationManagementService;
  retirementProduct?: ExpertInquiryIdentityRetirementProduct;
  consumerLoan?: ExpertInquiryIdentityConsumerLoan;
  insuranceProduct?: ExpertInquiryIdentityInsuranceProduct;
  acceptanceDevice?: ExpertInquiryIdentityAcceptanceDevice;
  ecommerce?: ExpertInquiryIdentityEcommerce;
  factoring?: ExpertInquiryIdentityFactoring;
  billingService?: ExpertInquiryIdentityBillingService;
  loyaltyService?: ExpertInquiryIdentityLoyaltyService;
  internationalImplementation?: ExpertInquiryIdentityInternationalImplementation;
}
