/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Amount} from './amount';

/**
 * Object représentant les données du contrat
 */
export interface ExpertInquiryFinancingAgreement {
  /**
   * Date de demande de financement
   */
  date?: string;
  amount?: Amount;
  riskAmount?: Amount;
  /**
   * Pourcentage garanti
   */
  guaranteePercentage?: number;
  /**
   * Nombre de véhicule du contrat
   */
  vehicleNumber?: number;
  /**
   * Durée du contrat en nombre de mois (par défaut 60 mois)
   */
  contractDuration?: number;
  /**
   * Durée de validité de l'accord (par défaut 12 mois)
   */
  agreementValidityDuration?: number;
  /**
   * Reference de la dernière proposition/décision de financement par le conseiller
   */
  propositionReference?: string;
}
