/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ExpertInquiryBrandsItem} from './expertInquiryBrandsItem';
import {ExpertInquiryFinancingAgreement} from './expertInquiryFinancingAgreement';
import {ExpertInquiryVehicle} from './expertInquiryVehicle';

/**
 *  Cette structure doit contenir toutes les données fonctionnelles décrivant le lead Bail Auto
 */
export interface ExpertInquiryAutoLease {
  /**
   * Motif de la demande (Création 'C' ou Renouvellement 'R' ou Extension de parc 'E')
   */
  reason?: string;
  /**
   * Liste des différents marques de véhicules de la flotte
   */
  brands?: Array<ExpertInquiryBrandsItem>;
  vehicle?: ExpertInquiryVehicle;
  financingAgreement?: ExpertInquiryFinancingAgreement;
}
