/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Identifier} from './identifier';
import {ShortTypology} from './shortTypology';

/**
 *
 */
export interface ExpertInquiryIdentityCharacteristics {
  /**
   * Code Insee permettant l'identification d'un établissement ou d'une entreprise française (W)
   */
  siret?: string;
  expertInquiryStatus?: ShortTypology;
  expertInquiryType?: ShortTypology;
  legalEntityId?: Identifier;
  followUpProfessionalRoleId?: Identifier;
  /**
   * Raison sociale de la personne morale en relation avec l'organisme financier
   */
  companyName?: string;
  /**
   * date de création de la demande d'expertise
   */
  creationDate?: string;
  /**
   * date de dernière modification de la demande d'expertise
   */
  lastUpdate?: string;
  creatorProfessionalRoleId?: Identifier;
  instructionMode?: ShortTypology;
  implementationDelayType?: ShortTypology;
}
