/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Amount} from './amount';

/**
 * Object représentant les données du contrat
 */
export interface ExpertInquiryIdentityFinancingAgreement {
  /**
   * Date de demande de financement
   */
  date?: string;
  amount?: Amount;
}
