/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ExpertInquiryWebsiteOptionsItem} from './expertInquiryWebsiteOptionsItem';

/**
 * Cette structure doit contenir toutes les données fonctionnelles décrivant le lead Ecommerce
 */
export interface ExpertInquiryIdentityEcommerce {
  /**
   * Indique si le client possède déjà un site internet
   */
  existingWebsiteIndicator?: boolean;
  /**
   * Liste des options souscrites pour la création du site web
   */
  websiteOptions?: Array<ExpertInquiryWebsiteOptionsItem>;
  /**
   * Indique si le client vient d'une campagne commerciale
   */
  commercialCampaignIndicator?: boolean;
  /**
   * Nom de la campagne commerciale
   */
  commercialCampaignName?: string;
  /**
   * Indique si le client dispose de plusieurs entreprises avec des besoins e-commerce
   */
  multipleNeedsIndicator?: boolean;
}
