/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Cette structure doit contenir toutes les données fonctionnelles décrivant le lead Factor
 */
export interface ExpertInquiryFactoring {
  /**
   * Date d'entrée en relation
   */
  connectionDate?: string;
  /**
   * Indique si la demande est une demande Flashfacture (sinon Affacturage)
   */
  flashfactureIndicator?: boolean;
}
