/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Cette structure doit contenir les identifiants potentiels de la ressource. Ceux qui sont susceptibles d'être utilisés pour identifier la ressource.
 */
export interface ExpertInquiryIdentification {
  /**
   * Identifiant interne du lead
   */
  expertInquiryId?: string;
}
