/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Identifier} from './identifier';
import {ShortTypology} from './shortTypology';

/**
 *
 */
export interface ExpertInquiryCharacteristics {
  /**
   * Code Insee permettant l'identification d'un établissement ou d'une entreprise française (W)
   */
  siret?: string;
  /**
   * Code Insee permettant l'identification d'un établissement ou d'une entreprise française (W)
   */
  siren?: string;
  /**
   * Code de la banque (Format code Banque de France 5 Digits)
   */
  bankCode?: string;
  /**
   * Indique si PRO
   */
  professionalIndicator?: boolean;
  expertInquiryStatus?: ShortTypology;
  expertInquiryType?: ShortTypology;
  /**
   * Reference du dossier d'étude
   */
  opportunityReference?: string;
  legalEntityId?: Identifier;
  followUpProfessionalRoleId?: Identifier;
  /**
   * Raison sociale de la personne morale en relation avec l'organisme financier
   */
  companyName?: string;
  /**
   * date de création de la demande d'expertise
   */
  creationDate?: string;
  /**
   * date de dernière modification de la demande d'expertise
   */
  lastUpdate?: string;
  creatorProfessionalRoleId?: Identifier;
  instructionMode?: ShortTypology;
  implementationDelayType?: ShortTypology;
}
