/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ShortTypology} from './shortTypology';

/**
 * caractérisques de l'interaction de feedback
 */
export interface FeedbackCharacteristics {
  /**
   * Identifiant de la demande d'expertise
   */
  expertInquiryId: string;
  expertInquiryStatus?: ShortTypology;
  /**
   * Libellé de l'offre proposée au lead
   */
  proposedOfferLabel?: string;
  /**
   * Libellé de l'offre proposée au lead
   */
  expertInquiryProposedOffer?: string;
  comment?: string;
  internalComment?: string;
  /**
   * Nom de l'expert en contact avec le client
   */
  businessExpertName?: string;
  /**
   * Email de l'expert en contact avec le client
   */
  businessExpertEmail?: string;
  /**
   * Timestamp de dernière mise à jour dans le système de gestion de la relation client chez le producteur
   */
  lastUpdate?: string;
  /**
   * Changement de produit suite à l'entretien (conduira à la création d'une nouvelle demande d'expertise dans l'application MonExpert). Cas spécifique au producteur NIT.
   */
  newProduct?: string;
  /**
   *  Identifiant de la nouvelle demande d'expertise si un nouveau produit est indiqué (newProduct)
   */
  newExpertInquiryId?: string;
  /**
   * Plaque d'immatriculation du véhicule pour Lease
   */
  vehicleRegistration?: string;
}
