/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {FeedbackCharacteristics} from './feedbackCharacteristics';
import {FeedbackResponse} from './feedbackResponse';

/**
 * Ensemble des attributs susceptibles d'etre mis à jour suite à l'entretien client
 */
export interface Feedback {
  characteristics: FeedbackCharacteristics;
  response?: FeedbackResponse;
}
