/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Amount} from './amount';
import {PaymentSolutionsItem} from './paymentSolutionsItem';
import {ShortTypology} from './shortTypology';
import {WebsiteOptionsItem} from './websiteOptionsItem';

/**
 * Cette structure doit contenir toutes les données fonctionnelles décrivant le lead Ecommerce
 */
export interface InitiateEcommerceAttributes {
  nafn5?: ShortTypology;
  /**
   * Indique si le client possède déjà un site internet
   */
  existingWebsiteIndicator?: boolean;
  /**
   * Liste des options souscrites pour la création du site web
   */
  websiteOptions?: Array<WebsiteOptionsItem>;
  /**
   * Adresse URL du site client
   */
  websiteUrl?: string;
  paymentSolutions?: PaymentSolutionsItem;
  /**
   * Indique si le type de commerce effectué est BtoB (sinon BtoC)
   */
  btobIndicator?: boolean;
  annualRevenue?: Amount;
  /**
   * Indique si le chiffre d'affaire Ecommerce est réel (sinon prévisionnel)
   */
  realEcommerceAnnualRevenueIndicator?: boolean;
  annualEcommerceRevenue?: Amount;
  /**
   * Indique si le client vient d'une campagne commerciale
   */
  commercialCampaignIndicator?: boolean;
  /**
   * Nom de la campagne commerciale
   */
  commercialCampaignName?: string;
  /**
   * Indique si le client dispose de plusieurs entreprises avec des besoins e-commerce
   */
  multipleNeedsIndicator?: boolean;
}
