/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateFactoringAttributes} from './initiateFactoringAttributes';
import {InitiateFactoringCharacteristics} from './initiateFactoringCharacteristics';
import {InitiateFactoringResponse} from './initiateFactoringResponse';

/**
 * Sous-Ressource d'interaction permettant la creation d'une demande d'expertise Factor
 */
export interface InitiateFactoring {
  characteristics?: InitiateFactoringCharacteristics;
  attributes?: InitiateFactoringAttributes;
  response?: InitiateFactoringResponse;
}
