/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateAcceptanceDeviceAttributes} from './initiateAcceptanceDeviceAttributes';
import {InitiateAcceptanceDeviceCharacteristics} from './initiateAcceptanceDeviceCharacteristics';
import {InitiateAcceptanceDeviceResponse} from './initiateAcceptanceDeviceResponse';

/**
 * Sous-Ressource d'interaction permettant la creation d'une demande d'expertise TPE Santé
 */
export interface InitiateAcceptanceDevice {
  characteristics?: InitiateAcceptanceDeviceCharacteristics;
  attributes?: InitiateAcceptanceDeviceAttributes;
  response?: InitiateAcceptanceDeviceResponse;
}
