/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateConsumerLoanAttributes} from './initiateConsumerLoanAttributes';
import {InitiateConsumerLoanCharacteristics} from './initiateConsumerLoanCharacteristics';
import {InitiateConsumerLoanResponse} from './initiateConsumerLoanResponse';

/**
 * Sous-Ressource d'interaction permettant la creation d'une demande d'expertise crédit consommation Oney
 */
export interface InitiateConsumerLoan {
  characteristics?: InitiateConsumerLoanCharacteristics;
  attributes?: InitiateConsumerLoanAttributes;
  response?: InitiateConsumerLoanResponse;
}
