/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateServiceVoucherAttributes} from './initiateServiceVoucherAttributes';
import {InitiateServiceVoucherCharacteristics} from './initiateServiceVoucherCharacteristics';
import {InitiateServiceVoucherResponse} from './initiateServiceVoucherResponse';

/**
 * Sous-Ressource d'interaction permettant la creation d'une demande d'expertise NIT
 */
export interface InitiateServiceVoucher {
  characteristics?: InitiateServiceVoucherCharacteristics;
  response?: InitiateServiceVoucherResponse;
  attributes?: InitiateServiceVoucherAttributes;
}
