/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {BrandsItem} from './brandsItem';
import {InitiateAutoLeaseFinancingAgreement} from './initiateAutoLeaseFinancingAgreement';
import {InitiateAutoLeaseVehicle} from './initiateAutoLeaseVehicle';

/**
 * Cette structure doit contenir toutes les données fonctionnelles décrivant le lead lease, nécessaires à sa création.
 */
export interface InitiateAutoLeaseAttributes {
  /**
   * Motif de la demande (Création 'C' ou Renouvellement 'R')
   */
  reason?: string;
  /**
   * Liste des différents marques de véhicules de la flotte
   */
  brands?: Array<BrandsItem>;
  vehicle?: InitiateAutoLeaseVehicle;
  financingAgreement?: InitiateAutoLeaseFinancingAgreement;
}
