/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateInternationalImplementationAttributes} from './initiateInternationalImplementationAttributes';
import {InitiateInternationalImplementationCharacteristics} from './initiateInternationalImplementationCharacteristics';
import {InitiateInternationalImplementationResponse} from './initiateInternationalImplementationResponse';

/**
 * Sous-Ressource d'interaction permettant la creation d'une demande d'expertise Pramex
 */
export interface InitiateInternationalImplementation {
  characteristics?: InitiateInternationalImplementationCharacteristics;
  attributes?: InitiateInternationalImplementationAttributes;
  response?: InitiateInternationalImplementationResponse;
}
