/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ShortTypology} from './shortTypology';

/**
 * Objet représentant les données liés au(x) véhicule(s) ainsi que les options
 */
export interface InitiateAutoLeaseVehicle {
  /**
   * Description du véhicule
   */
  description?: string;
  /**
   * Assurance proposée par Agence VAD, Chargé PRO/DA
   */
  insuranceSuggestedBy?: string;
  /**
   * Mise à disposition d'un véhicule de remplacement
   */
  replacementVehicleIndicator?: boolean;
  /**
   * Mise à disposition d'une carte pour le carburant
   */
  fuelCardIndicator?: boolean;
  /**
   * Mise à disposition de pneumatiques de remplacement en cas d'usure
   */
  replacementTiresIndicator?: boolean;
  /**
   * Mise à disposition d'un badge LiberT
   */
  libertBadgeIndicator?: boolean;
  /**
   * Majoration premier loyer
   */
  increaseFirstRentIndicator?: boolean;
  /**
   * Reprise ancien véhicule
   */
  recoveryOldVehiclesIndicator?: boolean;
  motorizationType?: ShortTypology;
}
