/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateBillingServiceAttributes} from './initiateBillingServiceAttributes';
import {InitiateBillingServiceCharacteristics} from './initiateBillingServiceCharacteristics';
import {InitiateBillingServiceResponse} from './initiateBillingServiceResponse';

/**
 * Sous-Ressource d'interaction permettant la creation d'une demande d'expertise Je Pilote
 */
export interface InitiateBillingService {
  characteristics?: InitiateBillingServiceCharacteristics;
  attributes?: InitiateBillingServiceAttributes;
  response?: InitiateBillingServiceResponse;
}
