/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateRetirementProductAttributes} from './initiateRetirementProductAttributes';
import {InitiateRetirementProductCharacteristics} from './initiateRetirementProductCharacteristics';
import {InitiateRetirementProductResponse} from './initiateRetirementProductResponse';

/**
 * Sous-Ressource d'interaction permettant la creation d'une demande d'expertise Interépargne
 */
export interface InitiateRetirementProduct {
  response?: InitiateRetirementProductResponse;
  attributes?: InitiateRetirementProductAttributes;
  characteristics?: InitiateRetirementProductCharacteristics;
}
