/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateAutoLeaseAttributes} from './initiateAutoLeaseAttributes';
import {InitiateAutoLeaseCharacteristics} from './initiateAutoLeaseCharacteristics';
import {InitiateAutoLeaseResponse} from './initiateAutoLeaseResponse';

/**
 * Ensemble des attributs permettant la création d'une demande d'expertise Bail Auto
 */
export interface InitiateAutoLease {
  characteristics: InitiateAutoLeaseCharacteristics;
  response?: InitiateAutoLeaseResponse;
  attributes?: InitiateAutoLeaseAttributes;
}
