/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Amount} from './amount';

/**
 * Object représentant les données du contrat
 */
export interface InitiateAutoLeaseFinancingAgreement {
  /**
   * Date du contrat
   */
  date?: string;
  /**
   * Montant du contrat
   */
  amount?: string;
  riskAmount?: Amount;
  /**
   * Pourcentage garanti
   */
  guaranteePercentage?: number;
  /**
   * Nombre de véhicule du contrat
   */
  vehicleNumber?: number;
  /**
   * Durée du contrat en nombre d'années
   */
  contractDuration?: number;
  /**
   * Durée de validité de l'accord (par défaut 12 mois)
   */
  agreementValidityDuration?: number;
}
