/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateOrganizationManagementServiceAttributes} from './initiateOrganizationManagementServiceAttributes';
import {InitiateOrganizationManagementServiceCharacteristics} from './initiateOrganizationManagementServiceCharacteristics';
import {InitiateOrganizationManagementServiceResponse} from './initiateOrganizationManagementServiceResponse';

/**
 * Sous-Ressource d'interaction permettant la creation d'une demande d'expertise Ecotiz
 */
export interface InitiateOrganizationManagementService {
  characteristics?: InitiateOrganizationManagementServiceCharacteristics;
  response?: InitiateOrganizationManagementServiceResponse;
  attributes?: InitiateOrganizationManagementServiceAttributes;
}
