/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateInsuranceProductAttributes} from './initiateInsuranceProductAttributes';
import {InitiateInsuranceProductCharacteristics} from './initiateInsuranceProductCharacteristics';
import {InitiateInsuranceProductResponse} from './initiateInsuranceProductResponse';

/**
 * Sous-Ressource d'interaction permettant la creation d'une demande d'expertise Gras Savoye
 */
export interface InitiateInsuranceProduct {
  characteristics?: InitiateInsuranceProductCharacteristics;
  attributes?: InitiateInsuranceProductAttributes;
  response?: InitiateInsuranceProductResponse;
}
