/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InitiateLoyaltyServiceAttributes} from './initiateLoyaltyServiceAttributes';
import {InitiateLoyaltyServiceCharacteristics} from './initiateLoyaltyServiceCharacteristics';
import {InitiateLoyaltyServiceResponse} from './initiateLoyaltyServiceResponse';

/**
 * Sous-Ressource d'interaction permettant la creation d'une demande d'expertise Izicap
 */
export interface InitiateLoyaltyService {
  characteristics?: InitiateLoyaltyServiceCharacteristics;
  attributes?: InitiateLoyaltyServiceAttributes;
  response?: InitiateLoyaltyServiceResponse;
}
