/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Message} from './message';

/**
 * Message response object (BAPI)
 */
export interface MessageResponse {
  /**
   * list of messages
   */
  messages?: Array<Message>;
}
