/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Pagination (BAPI)
 */
export interface Page {
  /**
   * Number of items by page
   */
  pageSize?: number;
  /**
   * Total items
   */
  totalElement?: number;
  /**
   * Total pages
   */
  totalPages?: number;
  /**
   * Page number
   */
  pageNumber?: number;
  /**
   * Cle de reprise de la page courante
   */
  recoveryKey?: number;
}
