/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Objet composite Phone
 */
export interface Phone {
  /**
   * Indicatif téléphonique international
   */
  phoneCountryCode?: string;
  /**
   * Identifier value
   */
  value?: string;
}
