/**
 * productorExpert
 * productorExpert api for bapi Project
 *
 * OpenAPI spec version: 1.5.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Links} from './links';

/**
 * Response item
 */
export interface ResponseItem {
  /**
   * Identification
   */
  objectIdentification?: string;
  /**
   * Identify
   */
  objejctIdentity?: string;
  links?: Links;
}
