declare module libc3 {
    var lib: ng.IModule;
}

declare module libc3 {
    interface typo {
        key: string;
        value: string;
    }
    interface IOPTIONSCHOSEN {
        search_contains: string;
        LIBELLE_ONGLET_ADRESSE_COMMUNICATION: string;
        CODE_TYPE_ADRESSE_PRINCIPALE: string;
        CODE_TYPE_ADRESSE_CORRESPONDANCE: string;
        CODE_TYPE_ADRESSE_COMMUNICATION: string;
        no_results_text: string;
    }
    class OPTIONSCHOSEN implements IOPTIONSCHOSEN {
        search_contains: string;
        no_results_text: string;
        LIBELLE_ONGLET_ADRESSE_COMMUNICATION: string;
        CODE_TYPE_ADRESSE_PRINCIPALE: string;
        CODE_TYPE_ADRESSE_CORRESPONDANCE: string;
        CODE_TYPE_ADRESSE_COMMUNICATION: string;
    }
    interface IConstantes {
        OPTIONS_CHOSEN: IOPTIONSCHOSEN;
        TYPE_ACTION_ADD: number;
        TYPE_ACTION_DEL: number;
        TYPE_ACTION_MODIF_LEADER: number;
        TYPE_ACTION_INIT: number;
        TYPE_ACTION_MODIF_QUALITE: number;
        HOLDING: String;
        LIBELLE_SOUS_BLOC_DONNEES_INTERNES: string;
        LIBELLE_SOUS_BLOC_ETAT_CIVIL: string;
        LIBELLE_SOUS_BLOC_COORDONNEES: string;
        LIBELLE_SOUS_BLOC_ACTIVITES_PRO: string;
        URL_SOUS_BLOC_ACTIVITES_PRO: string;
        SENS_DISPLAY_HORIZONTAL: string;
        SENS_DISPLAY_VERTICAL: string;
        MARQUE_COURANTE: string;
        DE_LA_MARQUE_COURANTE: string;
        INFOBULLE_LEADER: string;
        INFOBULLE_SIREN: string;
        INFOBULLE_ADRESSE: string;
        LIBELLE_CHAMP_FACULTATIF: string;
        LIBELLE_CHAMP_OBLIGATOIRE: string;
        LIBELLE_MESSAGE_ERREUR_LIENS: string;
        LIBELLE_MESSAGE_SUCCESS_LIENS: string;
        LIBELLE_MESSAGE_ERREUR_EFFACEMENT_TIERLIE: string;
        LIBELLE_MESSAGE_SUCCESS_EFFACEMENT_TIERLIE: string;
        LIBELLE_MESSAGE_SUCCESS_AJOUT_RELATION: string;
        LIBELLE_MESSAGE_ERREUR_AJOUT_RELATION: string;
        LIBELLE_MESSAGE_ERREUR_OBLIGATOIRE: string;
        LIBELLE_MESSAGE_ERREUR_EMAIL: string;
        LIBELLE_DATE_FIABILISATION: string;
        LIBELLE_BLOC_DONNEES_INTERNES: string;
        LIBELLE_BLOC_DONNEES_ADMINISTRATIVES: string;
        LIBELLE_BLOC_DONNEES_FINANCIERES: string;
        LIBELLE_BLOC_PIECES_JUSTIFICATIVES: string;
        LIBELLE_BLOC_BLOC_NOTE: string;
        LIBELLE_ONGLET_ADRESSE_PRINCIPALE: string;
        LIBELLE_ONGLET_ADRESSE_CORRESPONDANCE: string;
        LIBELLE_SOUS_BLOC_PROFESSION: string;
        LIBELLE_SOUS_BLOC_REVENUS: string;
        LIBELLE_SOUS_BLOC_CHARGES: string;
        LIBELLE_SOUS_BLOC_SYNTHESE_REVENUS: string;
        LIBELLE_SOUS_BLOC_PATRIMOINE_IMMOBILIER: string;
        LIBELLE_SOUS_BLOC_PATRIMOINE_FINANCIER: string;
        LIBELLE_SOUS_BLOC_PIECES_JUSTIFICATIVES: string;
        LIBELLE_SOUS_BLOC_PROJETS: string;
        LIBELLE_SOUS_BLOC_HERITIERS: string;
        LIBELLE_SOUS_BLOC_SUCCESSION: string;
        LIBELLE_SOUS_BLOC_SENSIBILITES: string;
        LIBELLE_SOUS_BLOC_RELATION: string;
        LIBELLE_SOUS_BLOC_BLOC_NOTE: string;
        ID_BLOC_DONNEES_INTERNES: string;
        ID_BLOC_DONNEES_ADMINISTRATIVES: string;
        ID_BLOC_DONNEES_FINANCIERES: string;
        ID_BLOC_PIECES_JUSTIFICATIVES: string;
        ID_BLOC_BLOC_NOTE: string;
        ID_SOUS_BLOC_DONNEES_INTERNES: string;
        ID_SOUS_BLOC_ETAT_CIVIL: string;
        ID_SOUS_BLOC_COORDONNEES: string;
        ID_SOUS_BLOC_PROFESSION: string;
        ID_SOUS_BLOC_REVENUS: string;
        ID_SOUS_BLOC_CHARGES: string;
        ID_SOUS_BLOC_SYNTHESE_REVENUS: string;
        ID_SOUS_BLOC_PATRIMOINE_IMMOBILIER: string;
        ID_SOUS_BLOC_PATRIMOINE_FINANCIER: string;
        ID_SOUS_BLOC_PIECES_JUSTIFICATIVES: string;
        ID_SOUS_BLOC_PROJETS: string;
        ID_SOUS_BLOC_HERITIERS: string;
        ID_SOUS_BLOC_SUCCESSION: string;
        ID_SOUS_BLOC_SENSIBILITES: string;
        ID_SOUS_BLOC_RELATION: string;
        ID_SOUS_BLOC_BLOC_NOTE: string;
        URL_SOUS_BLOC_DONNEES_INTERNES: string;
        URL_SOUS_BLOC_ETAT_CIVIL: string;
        URL_SOUS_BLOC_COORDONNEES: string;
        URL_SOUS_BLOC_PROFESSION: string;
        URL_SOUS_BLOC_REVENUS: string;
        URL_SOUS_BLOC_CHARGES: string;
        URL_SOUS_BLOC_SYNTHESE_REVENUS: string;
        URL_SOUS_BLOC_PATRIMOINE_IMMOBILIER: string;
        URL_SOUS_BLOC_PATRIMOINE_FINANCIER: string;
        URL_SOUS_BLOC_PIECES_JUSTIFICATIVES: string;
        URL_SOUS_BLOC_PROJETS: string;
        URL_SOUS_BLOC_HERITIERS: string;
        URL_SOUS_BLOC_SUCCESSION: string;
        URL_SOUS_BLOC_RELATION: string;
        URL_SOUS_BLOC_BLOC_NOTE: string;
        SHOW_ON_CREATE_SOUS_BLOC_DONNEES_INTERNES: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_ETAT_CIVIL: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_COORDONNEES: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_PROFESSION: boolean;
        SHOW_ON_CREATE_BLOC_DONNEES_FINANCIERES: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_REVENUS: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_CHARGES: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_SYNTHESE_REVENUS: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_PATRIMOINE_IMMOBILIER: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_PATRIMOINE_FINANCIER: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_PIECES_JUSTIFICATIVES: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_PROJETS: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_HERITIERS: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_SUCCESSION: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_SENSIBILITES: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_RELATION: boolean;
        SHOW_ON_CREATE_SOUS_BLOC_NOTE: boolean;
        CIVILITE_MDE: string;
        CIVILITE_MLLE: string;
        CIVILITE_M: string;
        SITUATION_FAMILLE_INSTANCE_DIVORCE: number;
        SITUATION_FAMILLE_MARIE: number;
        CAPACITE_JURIDIQUE_TUTELLE: string[];
        TYPO_CIVILITE: string;
        TYPO_SITUATION_FAMILIALE: string;
        TYPO_PAYS: string;
        TYPO_NATIONALITE: string;
        TYPO_INDICATIF_TEL: string;
        TYPO_CAPACITE_JURIDIQUE: string;
        TYPO_SITUATION_FAMILLE: string;
        TYPO_CLAUSE_REGIME: string;
        TYPO_REGIME_MATRIMONIAL: string;
        TYPO_SITUATION_PROFESSIONNELLE: string;
        TYPO_FAMILLES_CHARGES_REVENUS: string;
        TYPO_CHARGE: string;
        TYPO_CHARGE_IMPOTS_FISCALITE: string;
        TYPO_REVENU: string;
        TYPO_USAGE: string;
        TYPO_HABITATION: string;
        TYPO_BIEN: string;
        TYPO_PIECES_JUSTIFICATIVES: string;
        TYPO_RELATION_LIENS: string;
        TYPO_RELATION_QUALITE: string;
        TYPO_FAMILLE_LIENS: string;
        TYPO_NATURE_OCCUPATION: string;
        TYPO_PATRIMOINE_FINANCIER: string;
        TYPO_PERIODICITE_PATRIMOINE_FINANCIER: string;
        TYPO_THEMES_SENSIBILITE: string;
        TYPO_SOUSTHEMES_SENSIBILITE: string;
        TYPO_PERIODICITE_REVENU: string;
        TYPO_PERIODICITE_CHARGE: string;
        TYPO_PROJETS: string;
        TYPO_METIERS: string;
        TYPO_LIEN_HERITIERS: string;
        TYPO_SECTEUR_EMPLOI: string;
        TYPO_FAMILLE_APE: string;
        TYPO_INFO_BANCAIRE: string;
        TYPO_SOUSFAMILLE_NAF: string;
        TYPO_CATEG_JURIDIQUE: string;
        TYPO_CATEG_JURIDIQUE_COMPLETE: string;
        TYPO_LISTE_CODE_NAF: string;
        TYPO_RESEAU_CE: string;
        TYPO_MOTS_CNIL: string;
        TYPE_PIECE_CI: string;
        TYPE_PIECE_QUITANCE: string;
        TYPE_PIECE_FICHE_PAYE: string;
        TYPE_DONNEES_FINANCIERES_REVENUS: number;
        TYPE_DONNEES_FINANCIERES_CHARGES: number;
        TYPE_DONNEES_FINANCIERES_PATRIMOINE_IMMOBILIER: number;
        TYPE_DONNEES_FINANCIERES_PATRIMOINE_FINANCIER: number;
        CODE_NATURE_OCCUPATION_PROPRIETAIRE: string;
        TITRE_POPUP_AJOUTER: string;
        TITRE_POPUP_MODIFIER: string;
        TITRE_POPUP_REVENUS: string;
        TITRE_PANEL_REVENUS: string;
        TITRE_PANEL_REVENUS_AUTRE: string;
        TITRE_POPUP_CHARGES: string;
        TITRE_PANEL_CHARGES: string;
        TITRE_PANEL_CHARGES_AUTRE: string;
        TITRE_POPUP_PATRIMOINE_IMMOBILIER: string;
        TITRE_PANEL_PATRIMOINE_IMMOBILIER: string;
        TITRE_PANEL_AUTRE_PATRIMOINE_IMMOBILIER: string;
        TITRE_POPUP_PATRIMOINE_FINANCIER: string;
        TITRE_PANEL_PATRIMOINE_FINANCIER: string;
        TITRE_PANEL_AUTRE_PATRIMOINE_FINANCIER: string;
        TITRE_POPUP_PROJETS: string;
        TITRE_PANEL_PROJETS: string;
        TITRE_PANEL_PROJETS_AUTRE: string;
        TITRE_POPUP_TUTELLE: string;
        TITRE_PANEL_TUTELLE: string;
        TITRE_INDICATEUR_PRESENCE: string;
        TITRE_MONTANT: string;
        LIBELLE_AG_DOM_ABSENTE: string;
        LIBELLE_CONTACT_RELATION: string;
        LIBELLE_DOMICILIATION_DIFFERENTE: string;
        LIBELLE_BLOC_GROUPE: string;
        ID_BLOC_GROUPE: string;
        LIBELLE_BLOC_Administratif: string;
        ID_BLOC_ADMINISTRATIF: string;
        LIBELLE_SOUS_BLOC_ORGANIGRAMME: string;
        LIBELLE_SOUS_BLOC_GRAPPAGE: string;
        LIBELLE_SOUS_BLOC_SYNTHESE: string;
        LIBELLE_SOUS_BLOC_FINANCIER: string;
        LIBELLE_SOUS_BLOC_COMMERCIAL: string;
        LIBELLE_SOUS_BLOC_DOCUMENTS: string;
        LIBELLE_SOUS_BLOC_IDENTIFICATION: string;
        LIBELLE_SOUS_BLOC_LIENS: string;
        LIBELLE_SOUS_BLOC_COTATION: string;
        LIBELLE_SOUS_BLOC_REVISION: string;
        LIBELLE_SOUS_BLOC_ETABLISSEMENTS: string;
        LIBELLE_SOUS_BLOC_INFORMATIONS_INTERNES: string;
        LIBELLE_SOUS_BLOC_RISQUE: string;
        LIBELLE_SOUS_BLOC_DEFI: string;
        LIBELLE_SOUS_BLOC_EVENEMENTS: string;
        LIBELLE_SOUS_BLOC_FONCTIONNEMENT: string;
        LIBELLE_SOUS_BLOC_EQUIPEMENTS: string;
        LIBELLE_SOUS_CHAPITRE_ADMINISTRATIF: string;
        LIBELLE_SOUS_CHAPITRE_COMMERCIAL: string;
        ID_SOUS_BLOC_ORGANIGRAMME: string;
        URL_SOUS_BLOC_ORGANIGRAMME: string;
        SHOW_ON_CREATE_SOUS_BLOC_ORGANIGRAMME: boolean;
        ID_SOUS_BLOC_GRAPPAGE: string;
        URL_SOUS_BLOC_GRAPPAGE: string;
        SHOW_ON_CREATE_SOUS_BLOC_GRAPPAGE: boolean;
        ID_SOUS_BLOC_SYNTHESE: string;
        URL_SOUS_BLOC_SYNTHESE: string;
        SHOW_ON_CREATE_SOUS_BLOC_SYNTHESE: boolean;
        ID_SOUS_BLOC_FINANCIER: string;
        URL_SOUS_BLOC_FINANCIER: string;
        SHOW_ON_CREATE_SOUS_BLOC_FINANCIER: boolean;
        ID_SOUS_BLOC_COMMERCIAL: string;
        URL_SOUS_BLOC_COMMERCIAL: string;
        SHOW_ON_CREATE_SOUS_BLOC_COMMERCIAL: boolean;
        ID_SOUS_BLOC_DOCUMENTS: string;
        URL_SOUS_BLOC_DOCUMENTS: string;
        SHOW_ON_CREATE_SOUS_BLOC_DOCUMENTS: boolean;
        ID_SOUS_BLOC_IDENTIFICATION: string;
        URL_SOUS_BLOC_IDENTIFICATION: string;
        SHOW_ON_CREATE_SOUS_BLOC_IDENTIFICATION: boolean;
        ID_SOUS_BLOC_ETABLISSEMENTS: string;
        URL_SOUS_BLOC_ETABLISSEMENTS: string;
        SHOW_ON_CREATE_SOUS_BLOC_ETABLISSEMENTS: boolean;
        URL_SOUS_BLOC_INFORMATIONS_INTERNES: string;
        ID_SOUS_BLOC_LIENS: string;
        URL_SOUS_BLOC_LIENS: string;
        SHOW_ON_CREATE_SOUS_BLOC_LIENS: boolean;
        ID_SOUS_BLOC_COTATION: string;
        URL_SOUS_BLOC_COTATION: string;
        SHOW_ON_CREATE_SOUS_BLOC_COTATION: boolean;
        ID_SOUS_BLOC_REVISION: string;
        URL_SOUS_BLOC_REVISION: string;
        SHOW_ON_CREATE_SOUS_BLOC_REVISION: boolean;
        ID_SOUS_BLOC_RISQUE: string;
        URL_SOUS_BLOC_RISQUE: string;
        SHOW_ON_CREATE_SOUS_BLOC_RISQUE: boolean;
        ID_SOUS_BLOC_DEFI: string;
        URL_SOUS_BLOC_DEFI: string;
        SHOW_ON_CREATE_SOUS_BLOC_DEFI: boolean;
        ID_SOUS_BLOC_EVENEMENTS: string;
        URL_SOUS_BLOC_EVENEMENTS: string;
        SHOW_ON_CREATE_SOUS_BLOC_EVENEMENTS: boolean;
        ID_SOUS_BLOC_FONCTIONNEMENT: string;
        URL_SOUS_BLOC_FONCTIONNEMENT: string;
        SHOW_ON_CREATE_SOUS_BLOC_FONCTIONNEMENT: boolean;
        ID_SOUS_BLOC_EQUIPEMENTS: string;
        URL_SOUS_BLOC_EQUIPEMENTS: string;
        SHOW_ON_CREATE_SOUS_BLOC_EQUIPEMENTS: boolean;
        MEDIA_CODE_TYPE_MEDIA: any;
        MEDIA_CODE_TYPE_USAGE_MEDIA: any;
        LABEL_ADRESSE_INFORMATION_PROPRIETAIRE: string;
        CODE_TYPE_ADRESSE_PRINCIPALE: string;
        CODE_TYPE_ADRESSE_COMMUNICATION: string;
        CODE_TYPE_ADRESSE_CORRESPONDANCE: string;
        LIBELLE_ONGLET_ADRESSE_COMMUNICATION: string;
        LISTE_TYPE_TELEPHONES_OPPOSITION: any;
    }
    class Constantes implements IConstantes {
        HOLDING: string;
        TYPE_ACTION_ADD: number;
        TYPE_ACTION_DEL: number;
        TYPE_ACTION_MODIF_LEADER: number;
        TYPE_ACTION_MODIF_QUALITE: number;
        TYPE_ACTION_INIT: number;
        SENS_DISPLAY_HORIZONTAL: string;
        SENS_DISPLAY_VERTICAL: string;
        OPTIONS_CHOSEN: OPTIONSCHOSEN;
        MARQUE_COURANTE: string;
        DE_LA_MARQUE_COURANTE: string;
        INFOBULLE_SIREN: string;
        INFOBULLE_ADRESSE: string;
        INFOBULLE_LEADER: string;
        LIBELLE_CHAMP_FACULTATIF: string;
        LIBELLE_CHAMP_OBLIGATOIRE: string;
        LIBELLE_MESSAGE_ERREUR_OBLIGATOIRE: string;
        LIBELLE_MESSAGE_ERREUR_EMAIL: string;
        LIBELLE_MESSAGE_ERREUR_LIENS: string;
        LIBELLE_MESSAGE_SUCCESS_LIENS: string;
        LIBELLE_MESSAGE_ERREUR_EFFACEMENT_TIERLIE: string;
        LIBELLE_MESSAGE_SUCCESS_EFFACEMENT_TIERLIE: string;
        LIBELLE_MESSAGE_SUCCESS_AJOUT_RELATION: string;
        LIBELLE_MESSAGE_ERREUR_AJOUT_RELATION: string;
        LIBELLE_DATE_FIABILISATION: string;
        LIBELLE_BLOC_DONNEES_INTERNES: string;
        LIBELLE_BLOC_DONNEES_ADMINISTRATIVES: string;
        LIBELLE_BLOC_DONNEES_FINANCIERES: string;
        LIBELLE_BLOC_PIECES_JUSTIFICATIVES: string;
        LIBELLE_BLOC_BLOC_NOTE: string;
        LIBELLE_SOUS_BLOC_ACTIVITES_PRO: string;
        LIBELLE_ONGLET_ADRESSE_PRINCIPALE: string;
        LIBELLE_ONGLET_ADRESSE_CORRESPONDANCE: string;
        LIBELLE_ONGLET_ADRESSE_COMMUNICATION: string;
        CODE_TYPE_ADRESSE_PRINCIPALE: string;
        CODE_TYPE_ADRESSE_CORRESPONDANCE: string;
        CODE_TYPE_ADRESSE_COMMUNICATION: string;
        LIBELLE_SOUS_BLOC_DONNEES_INTERNES: string;
        LIBELLE_SOUS_BLOC_ETAT_CIVIL: string;
        LIBELLE_SOUS_BLOC_COORDONNEES: string;
        LIBELLE_SOUS_BLOC_PROFESSION: string;
        LIBELLE_SOUS_BLOC_REVENUS: string;
        LIBELLE_SOUS_BLOC_CHARGES: string;
        LIBELLE_SOUS_BLOC_SYNTHESE_REVENUS: string;
        LIBELLE_SOUS_BLOC_PATRIMOINE_IMMOBILIER: string;
        LIBELLE_SOUS_BLOC_PATRIMOINE_FINANCIER: string;
        LIBELLE_SOUS_BLOC_PIECES_JUSTIFICATIVES: string;
        LIBELLE_SOUS_BLOC_PROJETS: string;
        LIBELLE_SOUS_BLOC_HERITIERS: string;
        LIBELLE_SOUS_BLOC_SUCCESSION: string;
        LIBELLE_SOUS_BLOC_SENSIBILITES: string;
        LIBELLE_SOUS_BLOC_RELATION: string;
        LIBELLE_SOUS_BLOC_BLOC_NOTE: string;
        ID_BLOC_DONNEES_INTERNES: string;
        ID_BLOC_DONNEES_ADMINISTRATIVES: string;
        ID_BLOC_DONNEES_FINANCIERES: string;
        ID_BLOC_PIECES_JUSTIFICATIVES: string;
        ID_BLOC_BLOC_NOTE: string;
        ID_SOUS_BLOC_DONNEES_INTERNES: string;
        URL_SOUS_BLOC_DONNEES_INTERNES: string;
        SHOW_ON_CREATE_SOUS_BLOC_DONNEES_INTERNES: boolean;
        ID_SOUS_BLOC_ETAT_CIVIL: string;
        URL_SOUS_BLOC_ETAT_CIVIL: string;
        SHOW_ON_CREATE_SOUS_BLOC_ETAT_CIVIL: boolean;
        ID_SOUS_BLOC_COORDONNEES: string;
        URL_SOUS_BLOC_COORDONNEES: string;
        SHOW_ON_CREATE_SOUS_BLOC_COORDONNEES: boolean;
        ID_SOUS_BLOC_PROFESSION: string;
        URL_SOUS_BLOC_PROFESSION: string;
        URL_SOUS_BLOC_ACTIVITES_PRO: string;
        SHOW_ON_CREATE_SOUS_BLOC_PROFESSION: boolean;
        SHOW_ON_CREATE_BLOC_DONNEES_FINANCIERES: boolean;
        ID_SOUS_BLOC_REVENUS: string;
        URL_SOUS_BLOC_REVENUS: string;
        SHOW_ON_CREATE_SOUS_BLOC_REVENUS: boolean;
        ID_SOUS_BLOC_CHARGES: string;
        URL_SOUS_BLOC_CHARGES: string;
        SHOW_ON_CREATE_SOUS_BLOC_CHARGES: boolean;
        ID_SOUS_BLOC_SYNTHESE_REVENUS: string;
        URL_SOUS_BLOC_SYNTHESE_REVENUS: string;
        SHOW_ON_CREATE_SOUS_BLOC_SYNTHESE_REVENUS: boolean;
        ID_SOUS_BLOC_PATRIMOINE_IMMOBILIER: string;
        URL_SOUS_BLOC_PATRIMOINE_IMMOBILIER: string;
        SHOW_ON_CREATE_SOUS_BLOC_PATRIMOINE_IMMOBILIER: boolean;
        ID_SOUS_BLOC_PATRIMOINE_FINANCIER: string;
        URL_SOUS_BLOC_PATRIMOINE_FINANCIER: string;
        SHOW_ON_CREATE_SOUS_BLOC_PATRIMOINE_FINANCIER: boolean;
        ID_SOUS_BLOC_PIECES_JUSTIFICATIVES: string;
        URL_SOUS_BLOC_PIECES_JUSTIFICATIVES: string;
        SHOW_ON_CREATE_SOUS_BLOC_PIECES_JUSTIFICATIVES: boolean;
        ID_SOUS_BLOC_PROJETS: string;
        URL_SOUS_BLOC_PROJETS: string;
        SHOW_ON_CREATE_SOUS_BLOC_PROJETS: boolean;
        ID_SOUS_BLOC_SENSIBILITES: string;
        SHOW_ON_CREATE_SOUS_BLOC_SENSIBILITES: boolean;
        ID_SOUS_BLOC_HERITIERS: string;
        URL_SOUS_BLOC_HERITIERS: string;
        SHOW_ON_CREATE_SOUS_BLOC_HERITIERS: boolean;
        ID_SOUS_BLOC_SUCCESSION: string;
        URL_SOUS_BLOC_SUCCESSION: string;
        SHOW_ON_CREATE_SOUS_BLOC_SUCCESSION: boolean;
        ID_SOUS_BLOC_RELATION: string;
        URL_SOUS_BLOC_RELATION: string;
        SHOW_ON_CREATE_SOUS_BLOC_RELATION: boolean;
        ID_SOUS_BLOC_BLOC_NOTE: string;
        URL_SOUS_BLOC_BLOC_NOTE: string;
        SHOW_ON_CREATE_SOUS_BLOC_NOTE: boolean;
        CIVILITE_MDE: string;
        CIVILITE_MLLE: string;
        CIVILITE_M: string;
        SITUATION_FAMILLE_INSTANCE_DIVORCE: number;
        SITUATION_FAMILLE_MARIE: number;
        CAPACITE_JURIDIQUE_TUTELLE: string[];
        TYPO_CIVILITE: string;
        TYPO_SITUATION_FAMILIALE: string;
        TYPO_RELATION_LIENS: string;
        TYPO_RELATION_QUALITE: string;
        TYPO_PIECES_JUSTIFICATIVES: string;
        TYPO_FAMILLE_LIENS: string;
        TYPO_PAYS: string;
        TYPO_NATIONALITE: string;
        TYPO_INDICATIF_TEL: string;
        TYPO_CAPACITE_JURIDIQUE: string;
        TYPO_SITUATION_FAMILLE: string;
        TYPO_CLAUSE_REGIME: string;
        TYPO_REGIME_MATRIMONIAL: string;
        TYPO_SITUATION_PROFESSIONNELLE: string;
        TYPO_SECTEUR_EMPLOI: string;
        TYPO_FAMILLES_CHARGES_REVENUS: string;
        TYPO_CHARGE: string;
        TYPO_CHARGE_IMPOTS_FISCALITE: string;
        TYPO_REVENU: string;
        TYPO_USAGE: string;
        TYPO_HABITATION: string;
        TYPO_BIEN: string;
        TYPO_NATURE_OCCUPATION: string;
        TYPO_PATRIMOINE_FINANCIER: string;
        TYPO_PERIODICITE_PATRIMOINE_FINANCIER: string;
        TYPO_THEMES_SENSIBILITE: string;
        TYPO_SOUSTHEMES_SENSIBILITE: string;
        TYPO_PERIODICITE_REVENU: string;
        TYPO_PERIODICITE_CHARGE: string;
        TYPO_PROJETS: string;
        TYPO_METIERS: string;
        TYPO_LIEN_HERITIERS: string;
        TYPO_FAMILLE_APE: string;
        TYPO_SOUSFAMILLE_NAF: string;
        TYPO_CATEG_JURIDIQUE: string;
        TYPO_CATEG_JURIDIQUE_COMPLETE: string;
        TYPO_LISTE_CODE_NAF: string;
        TYPO_INFO_BANCAIRE: string;
        TYPO_RESEAU_CE: string;
        TYPO_MOTS_CNIL: string;
        TYPE_PIECE_CI: string;
        TYPE_PIECE_QUITANCE: string;
        TYPE_PIECE_FICHE_PAYE: string;
        TYPE_DONNEES_FINANCIERES_REVENUS: number;
        TYPE_DONNEES_FINANCIERES_CHARGES: number;
        TYPE_DONNEES_FINANCIERES_PATRIMOINE_IMMOBILIER: number;
        TYPE_DONNEES_FINANCIERES_PATRIMOINE_FINANCIER: number;
        CODE_NATURE_OCCUPATION_PROPRIETAIRE: string;
        TITRE_POPUP_AJOUTER: string;
        TITRE_POPUP_MODIFIER: string;
        TITRE_POPUP_REVENUS: string;
        TITRE_PANEL_REVENUS: string;
        TITRE_PANEL_REVENUS_AUTRE: string;
        TITRE_POPUP_CHARGES: string;
        TITRE_PANEL_CHARGES: string;
        TITRE_PANEL_CHARGES_AUTRE: string;
        TITRE_POPUP_PATRIMOINE_IMMOBILIER: string;
        TITRE_PANEL_PATRIMOINE_IMMOBILIER: string;
        TITRE_PANEL_AUTRE_PATRIMOINE_IMMOBILIER: string;
        TITRE_POPUP_PATRIMOINE_FINANCIER: string;
        TITRE_PANEL_PATRIMOINE_FINANCIER: string;
        TITRE_PANEL_AUTRE_PATRIMOINE_FINANCIER: string;
        TITRE_POPUP_PROJETS: string;
        TITRE_PANEL_PROJETS: string;
        TITRE_PANEL_PROJETS_AUTRE: string;
        TITRE_POPUP_TUTELLE: string;
        TITRE_PANEL_TUTELLE: string;
        TITRE_INDICATEUR_PRESENCE: string;
        TITRE_MONTANT: string;
        LIBELLE_AG_DOM_ABSENTE: string;
        LIBELLE_CONTACT_RELATION: string;
        LIBELLE_DOMICILIATION_DIFFERENTE: string;
        LIBELLE_BLOC_GROUPE: string;
        ID_BLOC_GROUPE: string;
        LIBELLE_BLOC_Administratif: string;
        ID_BLOC_ADMINISTRATIF: string;
        LIBELLE_SOUS_BLOC_ORGANIGRAMME: string;
        LIBELLE_SOUS_BLOC_GRAPPAGE: string;
        LIBELLE_SOUS_BLOC_SYNTHESE: string;
        LIBELLE_SOUS_BLOC_FINANCIER: string;
        LIBELLE_SOUS_BLOC_COMMERCIAL: string;
        LIBELLE_SOUS_BLOC_DOCUMENTS: string;
        LIBELLE_SOUS_BLOC_IDENTIFICATION: string;
        LIBELLE_SOUS_BLOC_LIENS: string;
        LIBELLE_SOUS_BLOC_COTATION: string;
        LIBELLE_SOUS_BLOC_REVISION: string;
        LIBELLE_SOUS_BLOC_ETABLISSEMENTS: string;
        LIBELLE_SOUS_BLOC_INFORMATIONS_INTERNES: string;
        LIBELLE_SOUS_BLOC_RISQUE: string;
        LIBELLE_SOUS_BLOC_DEFI: string;
        LIBELLE_SOUS_BLOC_EVENEMENTS: string;
        LIBELLE_SOUS_BLOC_FONCTIONNEMENT: string;
        LIBELLE_SOUS_BLOC_EQUIPEMENTS: string;
        LIBELLE_SOUS_CHAPITRE_ADMINISTRATIF: string;
        LIBELLE_SOUS_CHAPITRE_COMMERCIAL: string;
        ID_SOUS_BLOC_ORGANIGRAMME: string;
        URL_SOUS_BLOC_ORGANIGRAMME: string;
        SHOW_ON_CREATE_SOUS_BLOC_ORGANIGRAMME: boolean;
        ID_SOUS_BLOC_GRAPPAGE: string;
        URL_SOUS_BLOC_GRAPPAGE: string;
        SHOW_ON_CREATE_SOUS_BLOC_GRAPPAGE: boolean;
        ID_SOUS_BLOC_SYNTHESE: string;
        URL_SOUS_BLOC_SYNTHESE: string;
        SHOW_ON_CREATE_SOUS_BLOC_SYNTHESE: boolean;
        ID_SOUS_BLOC_FINANCIER: string;
        URL_SOUS_BLOC_FINANCIER: string;
        SHOW_ON_CREATE_SOUS_BLOC_FINANCIER: boolean;
        ID_SOUS_BLOC_COMMERCIAL: string;
        URL_SOUS_BLOC_COMMERCIAL: string;
        SHOW_ON_CREATE_SOUS_BLOC_COMMERCIAL: boolean;
        ID_SOUS_BLOC_DOCUMENTS: string;
        URL_SOUS_BLOC_DOCUMENTS: string;
        SHOW_ON_CREATE_SOUS_BLOC_DOCUMENTS: boolean;
        ID_SOUS_BLOC_IDENTIFICATION: string;
        URL_SOUS_BLOC_IDENTIFICATION: string;
        SHOW_ON_CREATE_SOUS_BLOC_IDENTIFICATION: boolean;
        ID_SOUS_BLOC_ETABLISSEMENTS: string;
        URL_SOUS_BLOC_ETABLISSEMENTS: string;
        SHOW_ON_CREATE_SOUS_BLOC_ETABLISSEMENTS: boolean;
        ID_SOUS_BLOC_INFORMATIONS_INTERNES: string;
        URL_SOUS_BLOC_INFORMATIONS_INTERNES: string;
        SHOW_ON_CREATE_SOUS_INFORMATIONS_INTERNES: boolean;
        ID_SOUS_BLOC_LIENS: string;
        URL_SOUS_BLOC_LIENS: string;
        SHOW_ON_CREATE_SOUS_BLOC_LIENS: boolean;
        ID_SOUS_BLOC_COTATION: string;
        URL_SOUS_BLOC_COTATION: string;
        SHOW_ON_CREATE_SOUS_BLOC_COTATION: boolean;
        ID_SOUS_BLOC_REVISION: string;
        URL_SOUS_BLOC_REVISION: string;
        SHOW_ON_CREATE_SOUS_BLOC_REVISION: boolean;
        ID_SOUS_BLOC_RISQUE: string;
        URL_SOUS_BLOC_RISQUE: string;
        SHOW_ON_CREATE_SOUS_BLOC_RISQUE: boolean;
        ID_SOUS_BLOC_EVENEMENTS: string;
        URL_SOUS_BLOC_EVENEMENTS: string;
        SHOW_ON_CREATE_SOUS_BLOC_EVENEMENTS: boolean;
        ID_SOUS_BLOC_FONCTIONNEMENT: string;
        URL_SOUS_BLOC_FONCTIONNEMENT: string;
        SHOW_ON_CREATE_SOUS_BLOC_FONCTIONNEMENT: boolean;
        ID_SOUS_BLOC_EQUIPEMENTS: string;
        URL_SOUS_BLOC_EQUIPEMENTS: string;
        SHOW_ON_CREATE_SOUS_BLOC_EQUIPEMENTS: boolean;
        ID_SOUS_BLOC_DEFI: string;
        URL_SOUS_BLOC_DEFI: string;
        SHOW_ON_CREATE_SOUS_BLOC_DEFI: boolean;
        MEDIA_CODE_TYPE_MEDIA: typo[];
        MEDIA_CODE_TYPE_USAGE_MEDIA: typo[];
        LABEL_ADRESSE_INFORMATION_PROPRIETAIRE: string;
        LISTE_TYPE_TELEPHONES_OPPOSITION: typo[];
    }
}

declare module libc3 {
    interface IContexte {
        init: () => any;
        read: () => any;
    }
    class Contexte implements IContexte {
        portailAgent: MyWay.Services.ServiceAgent;
        $q: ng.IQService;
        static $inject: string[];
        constructor(PortailAgent: MyWay.Services.ServiceAgent, $q: ng.IQService);
        _singletonData: any;
        init(): ng.IPromise<{}>;
        read(): any;
    }
}

declare module libc3 {
    interface ITools {
        getStrHeureCourante: () => any;
        getLibelleRevenuCharge: (code: any) => any;
        MsgBox: (header: any, msg: any, icon: any, size: any) => any;
        extractErreur: (data: any) => any;
        getStrDateCourante: () => any;
        getStrDateCouranteTiret: () => any;
        formatDateTiret: (d: any) => any;
    }
    class Tools implements ITools {
        modalService: any;
        static $inject: string[];
        constructor(modalService: any);
        getStrHeureCourante(): any;
        getLibelleRevenuCharge(code: any): any;
        MsgBox(header: any, msg: any, icon: any, size: any): any;
        extractErreur(data: any): any;
        getStrDateCourante(): any;
        getStrDateCouranteTiret(): any;
        formatDateTiret(d: any): any;
    }
}

declare module libc3 {
    interface IAdresseCorporateService {
        getAdresseCorporate: (idPersonne: any) => any;
        modifAdresseCorporate: (adresse: any) => any;
        creerAdresseCorporate: (adresse: any) => any;
    }
    class AdresseCorporateService implements IAdresseCorporateService {
        portailAgent: MyWay.Services.ServiceAgent;
        urlAdresseCorporate: any;
        contexte: IContexte;
        static $inject: string[];
        constructor(PortailAgent: MyWay.Services.ServiceAgent, urlAdresseCorporate: any, Contexte: IContexte);
        getAdresseCorporate(idPersonne: any): any;
        modifAdresseCorporate(adresse: any): any;
        creerAdresseCorporate(adresse: any): any;
    }
}

declare module libc3 {
    interface IMediaCorporateService {
        modifierMediaBdr: (media: any) => any;
        getMediaBdr: (identifiantPersonne: any) => any;
        getMediaBdd: (identifiantPersonne: any) => any;
        creerMediaBdr: (media: any) => any;
    }
    class MediaCorporateService implements IMediaCorporateService {
        portailAgent: MyWay.Services.ServiceAgent;
        urlMediaBdr: any;
        urlMediaBdd: any;
        contexte: IContexte;
        static $inject: string[];
        constructor(PortailAgent: MyWay.Services.ServiceAgent, urlMediaBdr: any, urlMediaBdd: any, Contexte: IContexte);
        getMediaBdr(identifiantPersonne: any): any;
        getMediaBdd(identifiantPersonne: any): any;
        modifierMediaBdr(media: any): any;
        creerMediaBdr(media: any): any;
    }
}

declare module libc3 {
    interface IProService {
        rechercherSiretAsync: (codeSiren: any) => any;
        rechercherRaisonSocialeAsync: (raisonSociale: any) => any;
        rechercherRaisonSocialeEtCodePostalAsync: (raisonSociale: any, codePostal: any) => any;
    }
    class ProService implements IProService {
        portailAgent: MyWay.Services.ServiceAgent;
        urlSiren: any;
        static $inject: string[];
        constructor(PortailAgent: MyWay.Services.ServiceAgent, urlSiren: any);
        rechercherSiretAsync(codeSiren: any): any;
        rechercherRaisonSocialeAsync(raisonSociale: any): any;
        rechercherRaisonSocialeEtCodePostalAsync(raisonSociale: any, codePostal: any): any;
    }
}

declare module libc3 {
    interface IRelationCorporateService {
        getPersonneOrganigramme: () => any;
        getRelationBDR(): any;
        initRelationBDR(idPersonne: any, callback: any): any;
        addPersonne(personneRecherche: any, critere: any): any;
        delPersonne(p: any): any;
        majRelationBDR(relationBDR: any): any;
        cancelRelationBDR(): any;
        getFlagModifRelationBDR(): any;
        isRelationBDRModif(): any;
        isDataObligatoire(dataName: any): any;
        initPersonneBDR(personneOrganigramme: any, callback: any): any;
        getPersonneBDR(): any;
        majPersonneBDR(callBack: any): any;
        isPersonneBDRModif(): any;
        getCompletudePersonneBDR(nomRubrique: any): any;
        cancelPersonneBDR(): any;
        getLeader(): any;
        modifPersonne(p: any, typeModification: any): any;
    }
    class RelationCorporateService implements IRelationCorporateService {
        constantes: IConstantes;
        contexte: IContexte;
        $http: ng.IHttpService;
        $q: ng.IQService;
        portailAgent: MyWay.Services.ServiceAgent;
        tiersLiesCorporateService: ITiersLiesCorporateService;
        urlCorporateInformation: any;
        urlRegroupementMarche: any;
        urlDonneeObligatoire: any;
        urlOrganigramme: any;
        urlRelationPrive: any;
        urlRelationPrive2: any;
        urlRelationPrive3: any;
        proService: IProService;
        mediaCorporateService: IMediaCorporateService;
        adresseCorporateService: IAdresseCorporateService;
        relationSI: any;
        _currentCodeMarche: any;
        _currentSecteurActivite: any;
        _listeDonneeObligatoire: any;
        _listeLibelle: any;
        personneSI: any;
        currentPersonneOrganigramme: any;
        personneSISave: any;
        codeQualiteSauvegarde: any;
        relationLOCALE: any;
        _tabLien: any;
        static $inject: string[];
        constructor($http: any, Constantes: IConstantes, Contexte: IContexte, $q: ng.IQService, PortailAgent: MyWay.Services.ServiceAgent, TiersLiesCorporateService: ITiersLiesCorporateService, ProService: IProService, AdresseCorporateService: IAdresseCorporateService, MediaCorporateService: IMediaCorporateService, urlCorporateInformation: any, urlRegroupementMarche: any, urlDonneeObligatoire: any, urlOrganigramme: any, urlRelationPrive: any, urlRelationPrive2: any, urlRelationPrive3: any);
        getPersonneOrganigramme(): any;
        getLeader(): any;
        initRelationBDR(idPersonne: any, callback: any): void;
        initPersonneBDR(personneOrganigramme: any, callback: any): void;
        getRelationBDR(): any;
        getPersonneBDR(): any;
        isPersonneBDRModif(): any;
        isRelationBDRModif(): any;
        addPersonne(personneRecherche: any, critere: any): any;
        delPersonne(p: any): any;
        modifPersonne(p: any, typeModification: any): any;
        majRelationBDR(relationBDR: any): any;
        cancelRelationBDR(): any;
        cancelPersonneBDR(): any;
        getFlagModifRelationBDR(): any;
        majPersonneBDR(callBack: any): void;
        isDataObligatoire(dataName: any): any;
        getCompletudePersonneBDR(nomRubrique: any): any;
        private consolideFromSIRENE(p, d);
        private getFlagObligatoire(item);
        private getLienFromData(data);
        private getSousLienFromData(data);
        private getInfoDataObligatoire(dao);
        private isRenseigne(p, data);
        private analyseCompletude(p, pMaj, nomRubrique);
        private majCompletude(p);
        private isDataComplete(p);
        private consolidePersonne(personne);
        private prepareForController(relation);
        private isBefore(p1, p2);
        private addSort(p, tab);
        private initReferentielLibelle(callback);
        private initReferentielDonneeObligatoire(callback);
        private initReferentielCodeMarche(callback);
        private requeteRelation(critere, callback);
        private addAdresseToPersonneBDR(listeAdresses);
        private consolidePersonneBDR(identifiantPersonne, callback);
        private getIndicePersonne(liste, personne);
        private getIndicePersonneLocale(personne);
        private newInformationCorporate(p);
        private newPersonneOrganigramme(c);
        private addPersonneSI(p);
        private modifPersonneSI(p, typeModification);
        private deletePersonneSI(p);
        private convertPersonneToRelationEconomique(p);
        private majMedia(m, identifiant);
        private createMedia(m, identifiant);
        private getDate();
    }
}

declare module libc3 {
    interface ITiersLiesCorporateService {
        getListeTypeLien: () => any;
        getListeTypeLienPersonnePhysique: () => any;
        getListeTypeLienExterieurPhysique: () => any;
        getListeTypeLienExterieurMorale: () => any;
        getListeTypeLienInterlocuteur: () => any;
        isTiersLiesModif: () => any;
        getTiersLiesOrganigramme: (idPersonne: any, listePersonneOrganigramme: any, codeEtablissement: any) => any;
        initModifLien: () => void;
        cancelModifLien: () => void;
        getTiersLiesBDR: (idPersonne: any, codeEtablissement: any) => any;
        createTiersLiesBDR: (elem: any) => any;
        modifTiersLiesBDR: (elem: any) => any;
        deleteTiersLiesBDR: (elem: any) => any;
        validModifLien: (listePersonneOrganigramme: any) => any;
    }
    class TiersLiesCorporateService implements TiersLiesCorporateService {
        portailAgent: MyWay.Services.ServiceAgent;
        $q: ng.IQService;
        urlTiersLiesCorporate: any;
        tools: ITools;
        static $inject: string[];
        constructor(PortailAgent: MyWay.Services.ServiceAgent, $q: ng.IQService, Tools: any, urlTiersLiesCorporate: any);
        _listeTypeLien: any;
        _listeTypeLienPersonnePhysique: any;
        _listeTypeInterlocuteurs: any;
        _listeTypeLiensExterieursPhysique: any;
        _listeTypeLiensExterieursMorale: any;
        _tabLienEdit: any;
        getListeTypeLien(): any;
        getListeTypeLienPersonnePhysique(): any;
        validModifLien(listePersonneOrganigramme: any): any;
        getListeTypeLienExterieurPhysique(): any;
        getListeTypeLienExterieurMorale(): any;
        getListeTypeLienInterlocuteur(): any;
        isTiersLiesModif(): any;
        getTiersLiesOrganigramme(idPersonne: any, listePersonneOrganigramme: any, codeEtablissement: any): any;
        initModifLien(): void;
        cancelModifLien(): void;
        getTiersLiesBDR(idPersonne: any, codeEtablissement: any): any;
        createTiersLiesBDR(elem: any): any;
        modifTiersLiesBDR(elem: any): any;
        deleteTiersLiesBDR(elem: any): any;
        private getTypeLienFromKey(key);
        private getStructureLien();
        private getLienFromPersonneOrganigramme(p);
        private getLienFromSI(item);
        private getPersonneLien(l, o);
        private consolideLien(o, p, tab);
        private isLienModif(lienSI, l);
        private getPersonneOrganigramme(id, l);
    }
}
